### ISSUE TITLE
Office Hours

### ISSUE THREAD

**Issue by mdogucu** [bayes-bats/tier2-schedule#1]
Could you please add your Zoom links for office hours @amy-herring and @monika76five? 

I thought us making separate zoom links would be better so that we are all hosts and avoid zoom issues but if you'd rather have one zoom link, I would be fine with that too.

**Comment by amy-herring** [comment]
Done!

From: Mine Dogucu ***@***.***>
Date: Wednesday, August 2, 2023 at 11:44 AM
To: bayes-bats/tier2-schedule ***@***.***>
Cc: Amy H Herring (she/her/hers) ***@***.***>, Mention ***@***.***>
Subject: [bayes-bats/tier2-schedule] Office Hours (Issue #1)

Could you please add your Zoom links for office hours @amy-herring<https://urldefense.com/v3/__https:/github.com/amy-herring__;!!OToaGQ!ssGKjynW7zbkCdwL3OUavnTfVxdRMenZA9p0ukOXpmLgRyukR7wd1nVQxaeMf5rbo2m-ysqNUJWWinR_01pZq4_W$> and @monika76five<https://urldefense.com/v3/__https:/github.com/monika76five__;!!OToaGQ!ssGKjynW7zbkCdwL3OUavnTfVxdRMenZA9p0ukOXpmLgRyukR7wd1nVQxaeMf5rbo2m-ysqNUJWWinR_0zKaQIDP$>?

I thought us making separate zoom links would be better so that we are all hosts and avoid zoom issues but if you'd rather have one zoom link, I would be fine with that too.

**Comment by monika76five** [comment]
Done too! Thanks!

**Comment by mdogucu** [comment]
@amy-herring I don't see your link or commit. Is it possible that you did not push?

**Comment by amy-herring** [comment]
Oh I put it on the notes Google doc.  Sorry I can fix the GitHub later (only have phone right now)

Sent from my iPhone

On Aug 2, 2023, at 7:50 PM, Mine Dogucu ***@***.***> wrote:

﻿

@amy-herring<https://urldefense.com/v3/__https://github.com/amy-herring__;!!OToaGQ!pFJo1JD9Q8vyn17dM96Q3XfXXpBSZRBleGpgVcWL8vrjuomKObj5-2kNWpW70qn1YNdCExZuZRqmFAM-s2_40fJp$> I don't see your link or commit. Is it possible that you did not push?

**Comment by mdogucu** [comment]
I can get it from Google docs no worries!
